server:
  port: 8082
spring:
  application:
    name: Chirp BE

  data:
    redis:
      host: "redis-16774.c273.us-east-1-2.ec2.redns.redis-cloud.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 16774
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://db.nllyeuwnakaxmgvvpjuq.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
jwt:
  secret: ${JWT_SECRET_BASE64}
#    expiration-minutes: 15

chirpbe:
  email:
    verification:
      expiry-hours: 1
    password-reset:
      expiry-minutes: 15

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine).0.0.1